# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodzic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodzic',
            name='adres',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rodzic',
            name='kod_pocztowy',
            field=models.CharField(default=-62, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rodzic',
            name='miejscowosc',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rodzic',
            name='telefon',
            field=models.CharField(default=11111, max_length=11),
            preserve_default=False,
        ),
    ]
