# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 09:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rodzic', '0002_auto_20160604_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rodzic',
            name='user',
        ),
        migrations.AddField(
            model_name='rodzic',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
